#!/usr/bin/env python3
"""Executive summary of the location-factor experiment, for people and agents.

Reads the committed JSON behind the three reports and writes
data/panel/LOCATION_FACTOR_SUMMARY.md: the question, the answer, how far each
finding goes, what the data cannot carry, where everything lives, and what is
still open. Every figure is read from the JSON, never typed, so the summary
cannot drift from the reports it summarises; the tests rebuild it byte for byte.

  location_factor_feasibility.json  (feasibility_location_factor.py, Phase 1)
  location_factor.json              (analyse_location_factor.py, Phase 2)
  land_value_vic.json               (analyse_land_value.py, Victoria)

Usage:  python3 scripts/summarise_location_factor.py [-o data/panel]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from analyse_location_factor import LAG_PRIMARY, est, f2, pval  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PANEL = ROOT / "data" / "panel"


def load(name):
    return json.loads((PANEL / name).read_text())


def pc(v):
    return f"{v:.0%}"


def check(lf):
    """Refuse to write if the findings the prose states no longer hold.

    The figures are read from the JSON, but the sentences around them make
    claims; if new data changes a claim, the summary must be rewritten, not
    regenerated with numbers that contradict it.
    """
    C = lf["corridor_shares"]["shares"]
    VL = lf["victoria"]["land"]
    B = lf["border"]
    conds = {
        "1: SDA concentrated in corridors like approvals, beyond population":
            C["new_build"] > 2 * C["persons"] and abs(C["new_build"] - C[f"approvals_lag{LAG_PRIMARY}"]) < 0.1,
        "2: Victoria, SDA leans cheaper on land, net of controls":
            VL["regression"] is not None and VL["regression"]["b"] < 0
            and abs(VL["regression"]["b"]) > 1.96 * VL["regression"]["se"],
        "2: Victoria, general building neutral on land": abs(VL["approvals"]["mean"]) < 0.1,
        "2: Victoria, placebo separates":
            VL["new_vs_population"]["p"] < 0.05 <= VL["existing"]["p"],
        "4: no border pull toward the higher factor":
            not any(c["p_flip"] < 0.05 and c["factor"]["b"] > 0 for c in B["cross"].values())
            and not (B["did"]["p_flip"] < 0.05 and B["did"]["b"] > 0),
    }
    failed = [k for k, ok in conds.items() if not ok]
    if failed:
        raise SystemExit("findings changed; rewrite the summary's prose for: " + "; ".join(failed))


def to_markdown(feas, lf, vic):
    hist = feas["pricing"]["history"]
    C = lf["corridor_shares"]["shares"]
    V = lf["victoria"]
    VL, VM = V["land"], V["mortgage"]
    P = lf["tests"]["primary"]["outcomes"]["new_build"]["rank"]
    reg = lf["tests"]["primary"]["outcomes"]["new_build"]["regression"]["coef"]["relative_log_cost"]
    B = lf["border"]
    bc, bn, did = B["cross"]["combined:full"], B["cross"]["new_build:full"], B["did"]
    dose = lf["tests"]["primary"]["outcomes"]["new_build"]["dose"]["interaction"]
    first, last = hist["versions"][0], hist["versions"][-1]
    changes = " and ".join(f"{e} v{v}" for e, v in hist["new_build_changes"])
    appr = f"approvals_lag{LAG_PRIMARY}"
    L = []
    w = L.append
    w("# Location-factor experiment: executive summary")
    w("")
    w("Generated by `scripts/summarise_location_factor.py` from the JSON behind the three reports; "
      "every figure is read from them, so do not edit by hand. Start here, then read the reports "
      "listed under *Where things are*. All findings are ecological: they compare regions' "
      "published totals and follow no dwelling, provider or participant.")
    w("")
    w("## The question")
    w("")
    w("The NDIS pays an SDA provider a base amount (set by building type, design category and "
      "features) times a **location factor** set per SA4 and building type. The factor is the same "
      "across every SA3 in an SA4, but land costs are not, so the margin is highest on the SA4's "
      "cheapest land. **Hypothesis:** providers therefore build new SDA in the cheapest SA3s within "
      "each SA4, more than ordinary housing does (a market developer's sale price rises with land "
      "value; SDA's payment does not).")
    w("")
    w("## The answer so far")
    w("")
    w(f"1. **New SDA is built where new housing is built.** The growth-corridor SA3s hold "
      f"{pc(C['new_build'])} of new SDA (Jun 2023–Jun 2026) against {pc(C[appr])} of dwelling "
      f"approvals, {pc(C['persons'])} of population, {pc(C['eligible_not_using'])} of participants "
      f"waiting for SDA and {pc(C['existing'])} of older SDA stock. *Solid, national.*")
    w(f"2. **Within an SA4, new SDA leans toward the cheaper land, as the hypothesis predicts.** In "
      f"Victoria, with Valuer-General vacant-land prices ({V['land_years'][0]}–{V['land_years'][1]}): "
      f"general building is neutral ({f2(VL['approvals']['mean'])}), new SDA leans cheaper net of "
      f"approvals, need, population and area (regression {est(VL['regression'])}; multinomial "
      f"{est(VL['multinomial'])}), and pre-NDIS SDA stock does not lean "
      f"({f2(VL['existing']['mean'])}, p {pval(VL['existing']['p'])}; new SDA "
      f"{f2(VL['new_vs_population']['mean'])}, p {pval(VL['new_vs_population']['p'])}). "
      f"*Suggestive: Victoria only, {VL['difference']['sa4s']} SA4s, inner Melbourne missing.*")
    w(f"3. **Nationally the question cannot be settled with the Census cost measure.** SDA sits in "
      f"cheaper SA3s than approvals ({f2(P['difference']['mean'])}, p {pval(P['difference']['p'])}; "
      f"regression {est(reg)}), but the 2021 median mortgage reads new housing as dear, so general "
      f"building appears to lean *dear* ({f2(P['approvals']['mean'])}), which inflates the gap. On "
      f"that measure pre-NDIS stock leans cheap as much as new SDA does. In Victoria the same "
      f"measure gives approvals {f2(VM['approvals']['mean'])} where land prices give "
      f"{f2(VL['approvals']['mean'])}: the mortgage measure is the problem, not the finding.")
    w(f"4. **No sign that the factor's level draws building.** Across {bc['pairs']} pairs of "
      f"adjacent SA3s either side of an SA4 border, the higher-factor side gets no more SDA per "
      f"approval, and with the post-2023 factors less ({est(bc['factor'])} per log point with pre-2023 factors, p {pval(bc['p_flip'])}; "
      f"{est(bn['factor'])} with post-2023 factors, p {pval(bn['p_flip'])}), nor did the July 2023 "
      f"re-set move building ({est(did)}, p {pval(did['p_flip'])}). The lean does not steepen where "
      f"cost spreads wider ({est(dose)} per SD). This does not contradict point 2: factors largely "
      "track costs, so across a border the extra payment mostly buys dearer land.")
    w("")
    w("**One-paragraph version:** New SDA is built where new housing is being built, concentrated "
      "in the growth corridors like other residential construction. In Victoria, where land prices "
      "can be measured directly, new SDA also leans toward the cheaper land within each region, "
      "beyond what general building, need or population explain, and older pre-NDIS stock does not "
      "— consistent with providers using a payment that is fixed across the SA4. There is no "
      "evidence that a higher factor, in itself, draws building across SA4 borders.")
    w("")
    w("## What the data cannot carry")
    w("")
    w("- **Victoria only for land cost.** NSW bulk land values are available only on request "
      "(requested; see *Open threads*). Queensland, South Australia and Western Australia publish no "
      "comparable free series.")
    w("- **SA3 publishes no building-type or category split of new build**, and a rise in enrolled "
      "HPS or Robust dwellings can include existing dwellings newly enrolled.")
    w("- **Lot prices, not prices per m².** VGV's vacant land is home sites under 4,000 m²; lots "
      "within that still vary in size.")
    w("- **Timing.** Building takes a year or more, so part of what was enrolled after the July 2023 "
      "factor re-set was committed before it.")
    w("- **Why, not just where.** Cheap land is also available land; providers also weigh "
      "participants, services, transport and hospitals. Need is controlled; the rest is not.")
    w("")
    w("## The pricing record")
    w("")
    w(f"`data/pricing/` holds every SDA Pricing Arrangements version from {first['edition']} "
      f"v{first['version']} to {last['edition']} v{last['version']} ({len(hist['versions'])} in all). "
      f"New-build location factors changed only in {changes}: until 30 June 2023 one table served "
      "all stock; from 1 July 2023 every new build uses a separate new-build table, unchanged since "
      "its January 2024 revision.")
    w("")
    w("## Where things are")
    w("")
    w("| File | What it is |")
    w("| --- | --- |")
    w("| `data/panel/LOCATION_FACTOR_FEASIBILITY.md` | Phase 1: data ingested, factor variation and changes between editions, how much identifying variation there is |")
    w("| `data/panel/LOCATION_FACTOR.md` | Phase 2: within-SA4 rank test, SA4 fixed-effects and multinomial regressions, border test, placebos, dose-response, robustness |")
    w("| `data/panel/LAND_VALUE_VIC.md` | Victoria: the within-SA4 tests again with vacant-land prices |")
    w("| `data/pricing/` | the NDIA pricing documents, `location_factors.csv`, `base_amounts.csv` (`scripts/extract_pricing.py`) |")
    w("| `data/abs/` | building approvals by SA2, Census 2021 by SA3/SA2, SA3 adjacency, locality-to-SA3 dwellings (`scripts/reduce_abs.py`, `scripts/build_sa3_adjacency.py`) |")
    w("| `data/vgv/` | Victorian vacant-land medians by locality (`scripts/reduce_vgv.py`) |")
    w("| `raw/MANIFEST.md` | every large download (git-ignored `raw/`): URL, release, licence, checksum |")
    w("| `data/README.md` | how each reduced file is built, and every name fix or exclusion |")
    w("")
    w("To rebuild the reports from committed files: `extract_pricing.py`, "
      "`feasibility_location_factor.py`, `analyse_land_value.py`, `analyse_location_factor.py`, "
      "then this script (the order matters: `LOCATION_FACTOR.md` quotes the Victorian results). "
      "`python3 -m unittest discover tests` checks every output byte for byte.")
    w("")
    w("## Open threads")
    w("")
    w("- **NSW land values.** Requested from the NSW Valuer General (bulk land values, all LGAs, "
      "1 July 2021 and latest base dates). When they arrive: keep property-level files in `raw/` "
      "(never `data/`, which is published), aggregate to SA3 by `data/abs/sal_sa3_dwellings.csv`, "
      "and run the `analyse_land_value.py` tests for NSW. A second large state would add SA4s, which "
      "the rank tests and the dose-response test on land prices both need.")
    w("- **More quarters.** Re-run everything as Supplement P editions are added; the before-and-after "
      "border comparison in particular needs a longer post-2023 window.")
    w("- **Nothing here changes the site.** `index.html`, `app.js` and `time/` are untouched.")
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("-o", "--out", default=str(PANEL))
    args = ap.parse_args(argv)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    lf = load("location_factor.json")
    check(lf)
    md = to_markdown(load("location_factor_feasibility.json"), lf, load("land_value_vic.json"))
    (out / "LOCATION_FACTOR_SUMMARY.md").write_text(md)
    print(f"wrote {out}/LOCATION_FACTOR_SUMMARY.md", file=sys.stderr)


if __name__ == "__main__":
    main()
